<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Kost_foto extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Kost_foto_model');
        $this->load->library('form_validation');        
	$this->load->library('datatables');
    }

    public function index()
    {
        $this->load->view('kost_foto/kost_foto_list');
    } 
    
    public function json() {
        header('Content-Type: application/json');
        echo $this->Kost_foto_model->json();
    }

    public function read($id) 
    {
        $row = $this->Kost_foto_model->get_by_id($id);
        if ($row) {
            $data = array(
		'id' => $row->id,
		'id_kost_detail' => $row->id_kost_detail,
		'foto' => $row->foto,
	    );
            $this->load->view('kost_foto/kost_foto_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('kost_foto'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('kost_foto/create_action'),
	    'id' => set_value('id'),
	    'id_kost_detail' => set_value('id_kost_detail'),
	    'foto' => set_value('foto'),
	);
        $this->load->view('kost_foto/kost_foto_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'id_kost_detail' => $this->input->post('id_kost_detail',TRUE),
		'foto' => $this->input->post('foto',TRUE),
	    );

            $this->Kost_foto_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('kost_foto'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Kost_foto_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('kost_foto/update_action'),
		'id' => set_value('id', $row->id),
		'id_kost_detail' => set_value('id_kost_detail', $row->id_kost_detail),
		'foto' => set_value('foto', $row->foto),
	    );
            $this->load->view('kost_foto/kost_foto_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('kost_foto'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id', TRUE));
        } else {
            $data = array(
		'id_kost_detail' => $this->input->post('id_kost_detail',TRUE),
		'foto' => $this->input->post('foto',TRUE),
	    );

            $this->Kost_foto_model->update($this->input->post('id', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('kost_foto'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Kost_foto_model->get_by_id($id);

        if ($row) {
            $this->Kost_foto_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('kost_foto'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('kost_foto'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('id_kost_detail', 'id kost detail', 'trim|required');
	$this->form_validation->set_rules('foto', 'foto', 'trim|required');

	$this->form_validation->set_rules('id', 'id', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Kost_foto.php */
/* Location: ./application/controllers/Kost_foto.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-11-17 06:09:37 */
/* http://harviacode.com */