<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Kost_detail_model extends CI_Model
{

    public $table = 'kost_detail';
    public $id = '';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json()
    {
        $this->datatables->select('kost_detail.id, kost.nama_kost,kost_detail.nama_kamar,kost_detail.deskripsi_kamar,kost_detail.harga,GROUP_CONCAT(kost_foto.foto) AS foto,kost_detail.fasilitas');
        $this->datatables->from('kost_detail');
        //add this line for join
        $this->datatables->join('kost', 'kost_detail.id_kost = kost.id', 'right');
        $this->datatables->join('kost_foto', 'kost_detail.id=kost_foto.kost_detail_id');
        $this->datatables->group_by('kost_detail.id');
        $this->datatables->add_column('action', anchor(site_url('kost_detail/read/$1'), 'Read') . " | " . anchor(site_url('kost_detail/update/$1'), 'Update') . " | " . anchor(site_url('kost_detail/delete/$1'), 'Delete', 'onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $query = $this->db->select('kost_detail.id, kost.id AS id_kost, kost.nama_kost, kost_detail.nama_kamar, kost_detail.deskripsi_kamar, kost_detail.harga, GROUP_CONCAT(kost_foto.foto) AS foto, kost_detail.fasilitas')
            ->from('kost_detail')
            ->join('kost', 'kost_detail.id_kost = kost.id')
            ->join('kost_foto', 'kost_detail.id=kost_foto.kost_detail_id')
            ->where('kost_detail.id', $id)
            ->get();
        return $query->row();
    }

    // get total rows
    function total_rows($q = NULL)
    {
        $this->db->like('', $q);
        $this->db->or_like('id', $q);
        $this->db->or_like('id_kost', $q);
        $this->db->or_like('nama_kamar', $q);
        $this->db->or_like('deskripsi_kamar', $q);
        $this->db->or_like('harga', $q);
        $this->db->or_like('fasilitas', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL)
    {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('', $q);
        $this->db->or_like('id', $q);
        $this->db->or_like('id_kost', $q);
        $this->db->or_like('nama_kamar', $q);
        $this->db->or_like('deskripsi_kamar', $q);
        $this->db->or_like('harga', $q);
        $this->db->or_like('fasilitas', $q);
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
        return $this->db->insert_id();
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }
}

/* End of file Kost_detail_model.php */
/* Location: ./application/models/Kost_detail_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-11-17 06:09:31 */
/* http://harviacode.com */